# Base image
FROM node:10.11 as builder

# Set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# Add '/usr/src/app/node_modules/.bin' to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# Install and cache dependencies
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g @angular/cli

# Add app
COPY . /usr/src/app

# Generate build
RUN ng build

##############
# PRODUCTION #
##############
FROM nginx:1.13.9-alpine

# Copy artifact build from the 'build environment'
COPY --from=builder /usr/src/app/dist/primeng-quickstart-cli /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Run nginx
CMD [ "nginx", "-g", "daemon off;" ]
